### ISSUE TITLE
Weird issue with zowie ec1-c

### ISSUE THREAD

**Issue by chalermla24** [jfedor2/hid-remapper#117]
Holding any normal mouse button (left, right, forward, backward, middle) while moving the mouse result in the button being "let go" and resume pressing again. Does not happen with other mice that I own afaik.
Using dual pico version.

https://github.com/jfedor2/hid-remapper/assets/14847342/41519589-90f0-4d5f-abb3-630572cb0e9a

**Comment by jfedor2** [comment]
I suspect some report descriptor shenanigans.

Could you try to dump the HID report descriptor using Wireshark and maybe some USB traffic? Disconnect the mouse, start the capture, then plug the mouse in (directly into your computer, not through HID Remapper), do some of the the things that trigger the weirdness and post the pcap file here?

**Comment by chalermla24** [comment]
Is this right?
[ec1c.zip](https://github.com/jfedor2/hid-remapper/files/14562938/ec1c.zip)

**Comment by jfedor2** [comment]
Yes, that's it!

The descriptors actually seem fine, but I noticed that the mouse sometimes sends zero-length reports, which could cause this behavior. I thought we were already ignoring those, but I checked and it turns out we only ignore them in the single Pico version.

Can you try this test firmware build and see if it makes a difference?

[ignore_empty_reports.zip](https://github.com/jfedor2/hid-remapper/files/14563345/ignore_empty_reports.zip)

**Comment by chalermla24** [comment]
Yup. Working perfectly now. Thank you
