### ISSUE TITLE
Support for standalone Linux app on (Raspbian)?

### ISSUE THREAD

**Issue by AdrianKielbowicz** [jfedor2/hid-remapper#33]
Hey, not sure if this is the right place to ask questions but here it goes.. Will the hid-remapper work as a standalone app on Raspbian or any other Linux OS?

I would like to use a full OS so pico is not cutting it for me.

If the answer is no, would you be able to recommend a similar software that allows keys to be re-mapped in software? I've been digging into xmodmap but still unsure if I can remap 1 key to multiple I.e. key number 1 for example to ALT+SHIFT+F18 etc.

**Comment by michelehokuto** [comment]
i don't understand your purpose. Do you want create custom shortcut on your rasperryPi/other distro?

**Comment by AdrianKielbowicz** [comment]
> i don't understand your purpose. Do you want create custom shortcut on your rasperryPi/other distro?

I would like to use the hid-remapper on a fully fledged OS like Raspbian and not just execute the code on a pico or custom board. So a standalone application is what I am after that you can run within Linux. Does that make sense?

**Comment by claviger-pc** [comment]
You could use xmk on Linux, but I think there are desktop specific remapping possibilities as well.
https://github.com/manna-harbour/xmk

**Comment by b-** [comment]
> > i don't understand your purpose. Do you want create custom shortcut on your rasperryPi/other distro?
> 
> I would like to use the hid-remapper on a fully fledged OS like Raspbian and not just execute the code on a pico or custom board. So a standalone application is what I am after that you can run within Linux. Does that make sense?

I understand what you want, and I think I could help, but before I get to that I need to say that I think you might be misunderstanding the point of this project and the Pico/custom board's purpose. You're not supposed to use the Raspberry Pi Pico as a computer at all. In the case of this project it's acting sort of as a mouse "driver" implemented in hardware. You plug your mouse (or other input device) into whatever you've programmed with the HID-remapper firmware, and then you plug the other end of that device into your computer. 

This way, your computer doesn't need to spend any extra CPU time remapping your inputs (which can add some latency and jitter, especially if the computer is under load from other things). In my opinion, HID drivers should almost invariably be running with near-realtime priority and performance so that you never have to worry about your computer keeping up with how fast you can type or click :)

_That said,_ if you really want to remap your input devices via software on your operating system, there are definitely some awesome projects out there to do so. I used a few myself before switching to hardware running QMK and this HID remapper. The big downsides to such software solutions are that if the software has a problem you might need to reboot your computer or something, and if you use more than one computer you'll need to set up something on each one you want to remap your inputs on. And for that matter, if you want to remap your inputs on more than one operating system you need to use a different software tool for each one.

But here's a list of things I used before coming across QMK and this repository:

For Linux, I have to mention [Interception-Tools](https://gitlab.com/interception/linux/tools). I used their example caps2esc script for the longest time.

For macOS, use [Karabiner-Elements](https://github.com/pqrs-org/Karabiner-Elements) and/or [Steermouse](https://www.plentycom.jp/en/steermouse/).

For Windows, use [X-Mouse Button Control](https://www.highrez.co.uk/downloads/XMouseButtonControl.htm) or [AutoHotkey](https://autohotkey.org).

All of these tools have their own pros and cons, but in my opinion the biggest problems with them are that they're all different. Even X11 and Wayland treat the mouse a little differently, so the behavior of these sorts of tools becomes entirely dependent on the computer you're using. If you use something like HID-remapper or a mouse/keyboard with QMK or similar firmware, or the XMK firmware proposed above, you'll solve all of these problems by sticking a dongle between your computer and your mouse.
